apiVersion: v1
kind: Service
metadata:
  labels:
    app: ads-network
  name: ads-network
  namespace: default
spec:
  ports:
  - name: http
    port: 9365
    protocol: TCP
    targetPort: 9365
  selector:
    app: ads-network
  sessionAffinity: None
  type: ClusterIP
